### ISSUE TITLE
Climate thermostat import fail

### ISSUE THREAD

**Issue by polcape** [martindybal/taphome-homeassistant#148]
Hi, 

I add to config yaml file two thermostat with heating_cooling_mode_id.

But both aren't imported in home assitant and I get this error in log

Seems that Cool have to be capitalize.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 595, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 714, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 412, in add_to_platform_start
    if (modes := self.hvac_modes) and len(modes) >= 2 and HVACMode.OFF in modes:
                 ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 324, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/taphome/climate.py", line 309, in hvac_modes
    return self.climate_controller.hvac_modes
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/taphome/climate.py", line 145, in hvac_modes
    return [HVACMode.OFF, HVACMode.HEAT, HVACMode.Cool, HVACMode.HEAT_COOL]
                                         ^^^^^^^^^^^^^
AttributeError: type object 'HVACMode' has no attribute 'Cool'. Did you mean: 'COOL'?
```

**Comment by polcape** [comment]
Change HVACMode.Cool to HVACMode.COOL in climate.py seems fix the issue

**Comment by martindybal** [comment]
@polcape can you send a PR with fix?

**Comment by polcape** [comment]
https://github.com/martindybal/taphome-homeassistant/pull/149

Done
